### ISSUE TITLE
Self references are not displayed as links

### ISSUE THREAD

**Issue by jdirocco** [DamianoNaraku/jjodel#15]
![image](https://user-images.githubusercontent.com/7288605/116200851-21625900-a739-11eb-8ac4-496b1815b2a3.png)

**Comment by DamianoNaraku** [comment]
![image](https://user-images.githubusercontent.com/32931357/118978735-f05ff780-b977-11eb-8431-578132b6a4e5.png)

Edges can have mid-points where they must transit, so the user can explicitly tell the path an edge must follow.
Now if there is a looping edge without explicit mid-points, 3 of them are deducted to make it visible.
If the user explicitly set some mid-points the behaviour is unchanged, and the edge will follow the path entered by the user.
