### ISSUE TITLE
New Class

### ISSUE THREAD

**Issue by apierantonio** [DamianoNaraku/jjodel#20]
quando si creano in sequenza delle nuove classi vengono create tutte sullo stesso punto, quindi sono sovrapposte e sembra che la creazione non avviene (anche se l'indice della classe cambia). E' possibile crearle in punti diversi in modo che l'utente si accorge che le classi sono state create ?

**Comment by DamianoNaraku** [comment]
The position for new elements now follows this rule
 
![image](https://user-images.githubusercontent.com/32931357/118979034-52206180-b978-11eb-99d6-c46465402e37.png)

If the center of the current visible area of the graph is empty, the element will take that place (Class_1)
If that place is filled, it will take the next empty space following a spiral (Class_2, Class_3, …)
