### ISSUE TITLE
Pointer mouse

### ISSUE THREAD

**Issue by apierantonio** [DamianoNaraku/jjodel#21]
Quando il mouse si trova su una zona del model element (metaclasse o istanza) che può essere usato per trascinare l'elemento, il puntatore deve cambiare da freccia a pointer

**Comment by DamianoNaraku** [comment]
Any non-input area can be used to drag the vertex, the pointer has changed for those areas.
A quick reminder:
Dragging while right-clicking will always allow to drag the vertex regardless of the area clicked inside it.
Dragging while holding the mouse wheel will always drag the whole graph, even if “clicking” a vertex. Useful if the graph is covered by a mass of close or overlapping vertex.
