### ISSUE TITLE
rendering box, color scheme, menu

### ISSUE THREAD

**Issue by apierantonio** [DamianoNaraku/jjodel#23]
Tutti i box ed i menu contestuali, tipo:

<img width="414" alt="image" src="https://user-images.githubusercontent.com/17876100/117940069-fa934d80-b308-11eb-934a-d82861b4a8fc.png">

devono avere i bordi arrotondati (eg border-radius: 2-4px). Per quanto riguarda i colori di tutto il tool dobbiamo usare dei color scheme (vedi https://coolors.co per iniziare, chiaramente bisogna scegliere dei colori con un livello elevato di contrasto, direi che il color scheme può essere parametrico cioe ne possiamo prevedere piu di uno e poi l'utente o noi scegliamo quello piu adatto).  

Per quanto riguarda il menu contestuale:

<img width="191" alt="image" src="https://user-images.githubusercontent.com/17876100/117940568-7c837680-b309-11eb-9303-fb7298ad0fe9.png">

userei un aspetto visuale più caratterizzante, per esempio: 

<img width="429" alt="image" src="https://user-images.githubusercontent.com/17876100/117940706-a341ad00-b309-11eb-8386-74955cfcd509.png">

oppure

<img width="264" alt="image" src="https://user-images.githubusercontent.com/17876100/117941040-ffa4cc80-b309-11eb-8efd-dfcb0d6b48c8.png">

**Comment by DamianoNaraku** [comment]
Aggiornato il menu contestuale e altre finestre secondo i suggerimenti.
![image](https://user-images.githubusercontent.com/32931357/118979264-9449a300-b978-11eb-97bb-f31a4965bb19.png)
Per quanto riguarda il color scheme è configurabile e ho pre-inserito alcuni color-scheme suggeriti da dei siti internet.
![image](https://user-images.githubusercontent.com/32931357/118979287-99a6ed80-b978-11eb-80a2-bc7fe73eb8e5.png)
Ad esempio con questa scelta di colori (opinabile)
![image](https://user-images.githubusercontent.com/32931357/118979297-9d3a7480-b978-11eb-90b2-f47845ac2524.png)
I vertici adesso hanno questa apparenza
![image](https://user-images.githubusercontent.com/32931357/118979346-a88da000-b978-11eb-90f8-195618aa2bc4.png)
I colori corrispondono nell’ordine a: sfondo, font, bordo, font-secondario.
I color scheme possono applicarsi a bersagli specifici, vertici, attributi, reference, parametri... ma anche all'intero sito.
